# Generated by Django 5.0.3 on 2024-03-25 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('theblog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='title_tag',
            field=models.CharField(default='fredai blognews', max_length=255),
        ),
    ]
